networks:
  phpinfo-2:
    internal: true
services:
  phpinfo-2:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 100m
        reservations:
          cpus: "0.1"
          memory: 100m
    expose:
    - "8080"
    healthcheck:
      interval: 15s
      retries: 3
      start_period: 10s
      #test: wget -q --spider http://localhost:8080
      timeout: 10s
    image: belcebus/phpinfo-2:2.0
    networks:
    - phpinfo-2
    ports:
    - 8080:8080
version: "3.8"
