name: CI Docker

on:
  push:
    branches:
    - docker

jobs:
  build-docker:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        name: Checkout!
        
      - name: test
        run: |
          docker build -t test .
          docker run -d --rm --name container-test test
          while [ true ]
          do \
            sleep 10 \
            docker exec container-test ps | grep 'php -f index.php' && break
          done
