name: CI Docker

on:
  push:
    branches:
    - docker

jobs:
  build-docker:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        name: Checkout!
        
      - name: test
        run: |
          set -x
          docker build -t test .
          docker run -d --name testcontainer test
          while [ true ]
          do \
            sleep 10
            docker exec testcontainer ps | grep 'php -f index.php' && break
          done
          while [ true ]
          do \
            sleep 10
            docker logs testcontainer 2>& 1 | grep 'Server started' && break
          done
